[[prefacio]]
[preface]
== Prefácio

Este livreto teve origem em um projeto de extensão _Sementes de luz: estabelecendo relacionamentos em Santa Rita_, no IFPB, campus de Santa Rita.

O projeto pretendia estabelecer relacionamentos com diversos segmentos da sociedade de Santa Rita, e criar parcerias para novas oportunidades de extensão, pesquisa e estágio no território de atuação do campus.


=== Equipe

Este livro foi produzido graças as ações da equipe do projeto:

.Membros da equipe
- Allana Barros de Lima
- Amanda Nunes Gomes Meira
- Ana Karla Alves da Silva
- Ana Klara de Sousa Galdino
- Eduardo de Santana Medeiros Alexandre
- Jaciele da Silva Barros
- Marina de Souza Alves Meireles
- Michel Pratini Bernardo da Silva
- Nathalia de França Pereira
- Samuel de Melo Neves


=== Desafios e Superação

Em todos os momentos surgem novos desafios e precisamos lidar com eles. Os depoimentos a seguir irão apresentar os desafios que os egressos (ex-alunos  do IFPB de Santa Rita) tiveram em sua vida, até agora.

Além dos desafios, eles irão falar como se sentiram e a estratégia que adotaram para superá-los.

A leitura é simples e rápida, mas espero que possa semear esperança no coração do(a) leitor(a).

=== Ilustrações

As ilustrações foram criadas por _Allana Barros de Lima_ e _Samuel de Melo Neves_.

=== Depoimentos

Os depoimentos de professores de Santa Rita (município e estado) e egressos do IFPB (Santa Rita) foram coletados e registrados através de Pseudônimos escolhidos por eles:


[cols="3*", options="header"]
|===
| Pseudônimo
| Profissão
| Idade

| Menina dezoito
|
| 18

| Pan, a coisa
| Estudante
| 19

| Cipriano
| Estudante
| 18


| @melo.ian
| Estudante
| 19

| Fernanda Leandro
| Professora
| 30


| Queen
| Professor
| 34


| Amelhinha
| Professora
| 50

| Marcos Dias
| Professor
| 46

|===


[quote, Eduardo de Santana Medeiros Alexandre]
____
Sou grato a todos que contribuíram, direto ou indiretamente, para elaboração deste livro.
____




////
Sempre terminar o arquivo com uma nova linha.
////
